language: python
python:
  - "3.7.6"
env:
  - SECRET_KEY=secretkey
  - ALLOWED_HOSTS = ALLOWED_HOSTS
install:
  - pip install -r requirements.txt
script:
  - python3 manage.py migrate
  - python3 manage.py test