# Generated by Django 3.0.4 on 2020-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200505_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='map',
            field=models.CharField(default='object.title', max_length=255),
        ),
    ]
