# Generated by Django 3.0.4 on 2020-05-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='map',
            field=models.CharField(default='{{ object.title }}', max_length=255),
        ),
    ]
