# Generated by Django 3.0.7 on 2020-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200506_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='goodtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
