# Generated by Django 3.0.7 on 2020-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_goodtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='good',
        ),
        migrations.AlterField(
            model_name='post',
            name='map',
            field=models.CharField(default='場所もしくは住所の入力で地図を表示', max_length=255),
        ),
    ]
